run: myC_new.g  myC_new_test.java
	java -cp antlr-3.5.2-complete-no-st3.jar org.antlr.Tool myC_new.g 
	javac -cp antlr-3.5.2-complete-no-st3.jar:. myC_new_test.java
	java -cp antlr-3.5.2-complete-no-st3.jar:. myC_new_test test4.c
